global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
    basic_auth:
      username: 'admin'
      password: 'admin'
      
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']