FROM node:18-alpine
RUN npm install -g serve
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL
RUN npm run build
CMD ["serve", "-s", "build"]